import { Column, Entity, PrimaryGeneratedColumn } from "typeorm"

@Entity()
export class estudiante{
    @PrimaryGeneratedColumn()
    id_estudiante:number
    @Column()
    id_tesis:number
    @Column()
    id_usuario:number
    @Column()
    sexo:string
    @Column()
    estado_civil:string
    @Column()
    genero:string
    @Column()
    tipo_colegio:string
    @Column()
    numero_hijos:number
    @Column()
    pais:string
    @Column()
    provincia:string
    @Column()
    ciudad:string
    @Column()
    parroquia:string
    @Column()
    direccion:string
    @Column()
    created_at:Date
    @Column()
    deleted_at:Date
    @Column()
    updated_at:Date
    @Column()
    status:number
}